name: my_workflow
on: push

jobs: 
 build-deploy:
  name: my_job
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2

  - name: npm run build
    run: cd frontend && npm install && npm run build
  
  - name: Deploy to Firebase
    uses: w9jds/firebase-action@master
    with:
      args: deploy --only hosting
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      PROJECT_PATH: ./frontend